import { createFileRoute } from "@tanstack/react-router";
import { fetchTokens, fetchFeed } from "@/server/bags";

// Lightweight JSON-RPC 2.0 implementation of the Model Context Protocol
// (Streamable HTTP transport). We avoid the @modelcontextprotocol/sdk's
// Node-only Server class so this works in the Cloudflare Worker SSR runtime.

type JsonRpcRequest = {
  jsonrpc: "2.0";
  id?: string | number | null;
  method: string;
  params?: Record<string, unknown>;
};

type JsonRpcResponse = {
  jsonrpc: "2.0";
  id: string | number | null;
  result?: unknown;
  error?: { code: number; message: string };
};

const SERVER_INFO = { name: "bagspulse-mcp", version: "1.0.0" };

const TOOLS = [
  {
    name: "get_bags_leaderboard",
    description: "Return top Bags-launched tokens ranked by 24h volume and market cap.",
    inputSchema: {
      type: "object",
      properties: {
        limit: { type: "number", description: "Number of tokens to return (max 50)", default: 10 },
        sortBy: { type: "string", enum: ["volume", "marketCap"], default: "volume" },
      },
    },
  },
  {
    name: "analyze_creator",
    description: "Compute a health score (0-100) for a Bags token creator from their launches.",
    inputSchema: {
      type: "object",
      required: ["creator"],
      properties: {
        creator: { type: "string", description: "Creator wallet address or username" },
      },
    },
  },
  {
    name: "get_pulse_fees",
    description: "Return total protocol fees generated by tokens routed through PulseRouter.",
    inputSchema: { type: "object", properties: {} },
  },
];

async function callTool(name: string, args: Record<string, unknown>) {
  if (name === "get_bags_leaderboard") {
    const limit = Math.min(Number(args.limit ?? 10), 50);
    const sortBy = args.sortBy === "marketCap" ? "marketCap" : "volume24h";
    const { tokens } = await fetchTokens();
    const sorted = [...tokens].sort((a, b) => (b as never)[sortBy] - (a as never)[sortBy]).slice(0, limit);
    return sorted.map((t) => ({
      mint: t.mint,
      symbol: t.symbol,
      name: t.name,
      marketCap: t.marketCap,
      volume24h: t.volume24h,
      feesEarnedTotal: t.feesEarnedTotal,
    }));
  }

  if (name === "analyze_creator") {
    const creator = String(args.creator ?? "");
    if (!creator) throw new Error("creator is required");
    const { tokens } = await fetchTokens();
    const launches = tokens.filter(
      (t) => t.creatorWallet === creator || t.creator.toLowerCase() === creator.toLowerCase(),
    );
    const totalMcap = launches.reduce((s, t) => s + t.marketCap, 0);
    const totalFees = launches.reduce((s, t) => s + t.feesEarnedTotal, 0);
    const graduated = launches.filter((t) => t.graduated).length;
    const graduationRate = launches.length ? graduated / launches.length : 0;
    // Simple weighted health score
    const score = Math.min(
      100,
      Math.round(
        Math.log10(totalMcap + 1) * 10 +
          Math.log10(totalFees + 1) * 8 +
          graduationRate * 30 +
          Math.min(launches.length, 10) * 2,
      ),
    );
    return {
      creator,
      launches: launches.length,
      graduated,
      graduationRate: Number(graduationRate.toFixed(3)),
      totalMarketCap: totalMcap,
      totalFeesSol: totalFees,
      healthScore: score,
    };
  }

  if (name === "get_pulse_fees") {
    const [{ tokens }, { events }] = await Promise.all([fetchTokens(), fetchFeed()]);
    const totalFeesSol = tokens.reduce((s, t) => s + t.feesEarnedTotal, 0);
    const fees24hUsd = tokens.reduce((s, t) => s + t.feesEarned24h, 0);
    return {
      totalFeesSol: Number(totalFeesSol.toFixed(4)),
      fees24hUsd: Number(fees24hUsd.toFixed(2)),
      tokensTracked: tokens.length,
      recentEvents: events.length,
    };
  }

  throw new Error(`Unknown tool: ${name}`);
}

async function handleRpc(req: JsonRpcRequest): Promise<JsonRpcResponse> {
  const id = req.id ?? null;
  try {
    if (req.method === "initialize") {
      return {
        jsonrpc: "2.0",
        id,
        result: {
          protocolVersion: "2024-11-05",
          capabilities: { tools: {} },
          serverInfo: SERVER_INFO,
        },
      };
    }
    if (req.method === "tools/list") {
      return { jsonrpc: "2.0", id, result: { tools: TOOLS } };
    }
    if (req.method === "tools/call") {
      const params = req.params ?? {};
      const name = String(params.name ?? "");
      const args = (params.arguments ?? {}) as Record<string, unknown>;
      const data = await callTool(name, args);
      return {
        jsonrpc: "2.0",
        id,
        result: {
          content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
        },
      };
    }
    if (req.method === "ping") {
      return { jsonrpc: "2.0", id, result: {} };
    }
    return { jsonrpc: "2.0", id, error: { code: -32601, message: `Method not found: ${req.method}` } };
  } catch (e) {
    return { jsonrpc: "2.0", id, error: { code: -32603, message: (e as Error).message } };
  }
}

const CORS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type, Authorization, mcp-session-id",
};

export const Route = createFileRoute("/api/mcp")({
  server: {
    handlers: {
      OPTIONS: async () => new Response(null, { status: 204, headers: CORS }),
      GET: async () =>
        new Response(
          JSON.stringify({
            name: SERVER_INFO.name,
            version: SERVER_INFO.version,
            transport: "streamable-http",
            tools: TOOLS.map((t) => t.name),
            usage: "POST JSON-RPC 2.0 requests to this endpoint.",
          }),
          { headers: { "Content-Type": "application/json", ...CORS } },
        ),
      POST: async ({ request }) => {
        let body: JsonRpcRequest | JsonRpcRequest[];
        try {
          body = (await request.json()) as JsonRpcRequest | JsonRpcRequest[];
        } catch {
          return new Response(
            JSON.stringify({ jsonrpc: "2.0", id: null, error: { code: -32700, message: "Parse error" } }),
            { status: 400, headers: { "Content-Type": "application/json", ...CORS } },
          );
        }
        const responses = Array.isArray(body)
          ? await Promise.all(body.map(handleRpc))
          : await handleRpc(body);
        return new Response(JSON.stringify(responses), {
          headers: { "Content-Type": "application/json", ...CORS },
        });
      },
    },
  },
});
