/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RouterRouteImport } from './routes/router'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TokenMintRouteImport } from './routes/token.$mint'
import { Route as ApiMcpRouteImport } from './routes/api.mcp'
import { Route as ApiLicensesConfirmRouteImport } from './routes/api.licenses.confirm'
import { Route as ApiActionsSubscribeRouteImport } from './routes/api.actions.subscribe'
import { Route as ApiPublicAgentRunRouteImport } from './routes/api.public.agent.run'

const RouterRoute = RouterRouteImport.update({
  id: '/router',
  path: '/router',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenMintRoute = TokenMintRouteImport.update({
  id: '/token/$mint',
  path: '/token/$mint',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLicensesConfirmRoute = ApiLicensesConfirmRouteImport.update({
  id: '/api/licenses/confirm',
  path: '/api/licenses/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiActionsSubscribeRoute = ApiActionsSubscribeRouteImport.update({
  id: '/api/actions/subscribe',
  path: '/api/actions/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentRunRoute = ApiPublicAgentRunRouteImport.update({
  id: '/api/public/agent/run',
  path: '/api/public/agent/run',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/feed': typeof FeedRoute
  '/leaderboard': typeof LeaderboardRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/router': typeof RouterRoute
  '/api/mcp': typeof ApiMcpRoute
  '/token/$mint': typeof TokenMintRoute
  '/api/actions/subscribe': typeof ApiActionsSubscribeRoute
  '/api/licenses/confirm': typeof ApiLicensesConfirmRoute
  '/api/public/agent/run': typeof ApiPublicAgentRunRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/feed': typeof FeedRoute
  '/leaderboard': typeof LeaderboardRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/router': typeof RouterRoute
  '/api/mcp': typeof ApiMcpRoute
  '/token/$mint': typeof TokenMintRoute
  '/api/actions/subscribe': typeof ApiActionsSubscribeRoute
  '/api/licenses/confirm': typeof ApiLicensesConfirmRoute
  '/api/public/agent/run': typeof ApiPublicAgentRunRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/feed': typeof FeedRoute
  '/leaderboard': typeof LeaderboardRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/router': typeof RouterRoute
  '/api/mcp': typeof ApiMcpRoute
  '/token/$mint': typeof TokenMintRoute
  '/api/actions/subscribe': typeof ApiActionsSubscribeRoute
  '/api/licenses/confirm': typeof ApiLicensesConfirmRoute
  '/api/public/agent/run': typeof ApiPublicAgentRunRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/docs'
    | '/feed'
    | '/leaderboard'
    | '/portfolio'
    | '/pricing'
    | '/router'
    | '/api/mcp'
    | '/token/$mint'
    | '/api/actions/subscribe'
    | '/api/licenses/confirm'
    | '/api/public/agent/run'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/docs'
    | '/feed'
    | '/leaderboard'
    | '/portfolio'
    | '/pricing'
    | '/router'
    | '/api/mcp'
    | '/token/$mint'
    | '/api/actions/subscribe'
    | '/api/licenses/confirm'
    | '/api/public/agent/run'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/docs'
    | '/feed'
    | '/leaderboard'
    | '/portfolio'
    | '/pricing'
    | '/router'
    | '/api/mcp'
    | '/token/$mint'
    | '/api/actions/subscribe'
    | '/api/licenses/confirm'
    | '/api/public/agent/run'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  DocsRoute: typeof DocsRoute
  FeedRoute: typeof FeedRoute
  LeaderboardRoute: typeof LeaderboardRoute
  PortfolioRoute: typeof PortfolioRoute
  PricingRoute: typeof PricingRoute
  RouterRoute: typeof RouterRoute
  ApiMcpRoute: typeof ApiMcpRoute
  TokenMintRoute: typeof TokenMintRoute
  ApiActionsSubscribeRoute: typeof ApiActionsSubscribeRoute
  ApiLicensesConfirmRoute: typeof ApiLicensesConfirmRoute
  ApiPublicAgentRunRoute: typeof ApiPublicAgentRunRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/router': {
      id: '/router'
      path: '/router'
      fullPath: '/router'
      preLoaderRoute: typeof RouterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token/$mint': {
      id: '/token/$mint'
      path: '/token/$mint'
      fullPath: '/token/$mint'
      preLoaderRoute: typeof TokenMintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/licenses/confirm': {
      id: '/api/licenses/confirm'
      path: '/api/licenses/confirm'
      fullPath: '/api/licenses/confirm'
      preLoaderRoute: typeof ApiLicensesConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/actions/subscribe': {
      id: '/api/actions/subscribe'
      path: '/api/actions/subscribe'
      fullPath: '/api/actions/subscribe'
      preLoaderRoute: typeof ApiActionsSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/run': {
      id: '/api/public/agent/run'
      path: '/api/public/agent/run'
      fullPath: '/api/public/agent/run'
      preLoaderRoute: typeof ApiPublicAgentRunRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  DocsRoute: DocsRoute,
  FeedRoute: FeedRoute,
  LeaderboardRoute: LeaderboardRoute,
  PortfolioRoute: PortfolioRoute,
  PricingRoute: PricingRoute,
  RouterRoute: RouterRoute,
  ApiMcpRoute: ApiMcpRoute,
  TokenMintRoute: TokenMintRoute,
  ApiActionsSubscribeRoute: ApiActionsSubscribeRoute,
  ApiLicensesConfirmRoute: ApiLicensesConfirmRoute,
  ApiPublicAgentRunRoute: ApiPublicAgentRunRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
