/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SwapRouteImport } from './routes/swap'
import { Route as RouterRouteImport } from './routes/router'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BasketsRouteImport } from './routes/baskets'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TokenMintRouteImport } from './routes/token.$mint'
import { Route as BasketsIdRouteImport } from './routes/baskets.$id'
import { Route as ApiMcpRouteImport } from './routes/api.mcp'
import { Route as ApiLicensesConfirmRouteImport } from './routes/api.licenses.confirm'
import { Route as ApiCronTasksRouteImport } from './routes/api.cron.tasks'
import { Route as ApiActionsSubscribeRouteImport } from './routes/api.actions.subscribe'
import { Route as ApiPublicWebhooksHeliusRouteImport } from './routes/api.public.webhooks.helius'
import { Route as ApiPublicRouterPartnerRouteImport } from './routes/api.public.router.partner'
import { Route as ApiPublicAgentRunRouteImport } from './routes/api.public.agent.run'

const SwapRoute = SwapRouteImport.update({
  id: '/swap',
  path: '/swap',
  getParentRoute: () => rootRouteImport,
} as any)
const RouterRoute = RouterRouteImport.update({
  id: '/router',
  path: '/router',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BasketsRoute = BasketsRouteImport.update({
  id: '/baskets',
  path: '/baskets',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenMintRoute = TokenMintRouteImport.update({
  id: '/token/$mint',
  path: '/token/$mint',
  getParentRoute: () => rootRouteImport,
} as any)
const BasketsIdRoute = BasketsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BasketsRoute,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLicensesConfirmRoute = ApiLicensesConfirmRouteImport.update({
  id: '/api/licenses/confirm',
  path: '/api/licenses/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronTasksRoute = ApiCronTasksRouteImport.update({
  id: '/api/cron/tasks',
  path: '/api/cron/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiActionsSubscribeRoute = ApiActionsSubscribeRouteImport.update({
  id: '/api/actions/subscribe',
  path: '/api/actions/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksHeliusRoute = ApiPublicWebhooksHeliusRouteImport.update({
  id: '/api/public/webhooks/helius',
  path: '/api/public/webhooks/helius',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRouterPartnerRoute = ApiPublicRouterPartnerRouteImport.update({
  id: '/api/public/router/partner',
  path: '/api/public/router/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentRunRoute = ApiPublicAgentRunRouteImport.update({
  id: '/api/public/agent/run',
  path: '/api/public/agent/run',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/baskets': typeof BasketsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/feed': typeof FeedRoute
  '/leaderboard': typeof LeaderboardRoute
  '/legal': typeof LegalRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/referrals': typeof ReferralsRoute
  '/router': typeof RouterRoute
  '/swap': typeof SwapRoute
  '/api/mcp': typeof ApiMcpRoute
  '/baskets/$id': typeof BasketsIdRoute
  '/token/$mint': typeof TokenMintRoute
  '/api/actions/subscribe': typeof ApiActionsSubscribeRoute
  '/api/cron/tasks': typeof ApiCronTasksRoute
  '/api/licenses/confirm': typeof ApiLicensesConfirmRoute
  '/api/public/agent/run': typeof ApiPublicAgentRunRoute
  '/api/public/router/partner': typeof ApiPublicRouterPartnerRoute
  '/api/public/webhooks/helius': typeof ApiPublicWebhooksHeliusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/baskets': typeof BasketsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/feed': typeof FeedRoute
  '/leaderboard': typeof LeaderboardRoute
  '/legal': typeof LegalRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/referrals': typeof ReferralsRoute
  '/router': typeof RouterRoute
  '/swap': typeof SwapRoute
  '/api/mcp': typeof ApiMcpRoute
  '/baskets/$id': typeof BasketsIdRoute
  '/token/$mint': typeof TokenMintRoute
  '/api/actions/subscribe': typeof ApiActionsSubscribeRoute
  '/api/cron/tasks': typeof ApiCronTasksRoute
  '/api/licenses/confirm': typeof ApiLicensesConfirmRoute
  '/api/public/agent/run': typeof ApiPublicAgentRunRoute
  '/api/public/router/partner': typeof ApiPublicRouterPartnerRoute
  '/api/public/webhooks/helius': typeof ApiPublicWebhooksHeliusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/baskets': typeof BasketsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/feed': typeof FeedRoute
  '/leaderboard': typeof LeaderboardRoute
  '/legal': typeof LegalRoute
  '/portfolio': typeof PortfolioRoute
  '/pricing': typeof PricingRoute
  '/referrals': typeof ReferralsRoute
  '/router': typeof RouterRoute
  '/swap': typeof SwapRoute
  '/api/mcp': typeof ApiMcpRoute
  '/baskets/$id': typeof BasketsIdRoute
  '/token/$mint': typeof TokenMintRoute
  '/api/actions/subscribe': typeof ApiActionsSubscribeRoute
  '/api/cron/tasks': typeof ApiCronTasksRoute
  '/api/licenses/confirm': typeof ApiLicensesConfirmRoute
  '/api/public/agent/run': typeof ApiPublicAgentRunRoute
  '/api/public/router/partner': typeof ApiPublicRouterPartnerRoute
  '/api/public/webhooks/helius': typeof ApiPublicWebhooksHeliusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/baskets'
    | '/dashboard'
    | '/docs'
    | '/feed'
    | '/leaderboard'
    | '/legal'
    | '/portfolio'
    | '/pricing'
    | '/referrals'
    | '/router'
    | '/swap'
    | '/api/mcp'
    | '/baskets/$id'
    | '/token/$mint'
    | '/api/actions/subscribe'
    | '/api/cron/tasks'
    | '/api/licenses/confirm'
    | '/api/public/agent/run'
    | '/api/public/router/partner'
    | '/api/public/webhooks/helius'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/baskets'
    | '/dashboard'
    | '/docs'
    | '/feed'
    | '/leaderboard'
    | '/legal'
    | '/portfolio'
    | '/pricing'
    | '/referrals'
    | '/router'
    | '/swap'
    | '/api/mcp'
    | '/baskets/$id'
    | '/token/$mint'
    | '/api/actions/subscribe'
    | '/api/cron/tasks'
    | '/api/licenses/confirm'
    | '/api/public/agent/run'
    | '/api/public/router/partner'
    | '/api/public/webhooks/helius'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/baskets'
    | '/dashboard'
    | '/docs'
    | '/feed'
    | '/leaderboard'
    | '/legal'
    | '/portfolio'
    | '/pricing'
    | '/referrals'
    | '/router'
    | '/swap'
    | '/api/mcp'
    | '/baskets/$id'
    | '/token/$mint'
    | '/api/actions/subscribe'
    | '/api/cron/tasks'
    | '/api/licenses/confirm'
    | '/api/public/agent/run'
    | '/api/public/router/partner'
    | '/api/public/webhooks/helius'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BasketsRoute: typeof BasketsRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DocsRoute: typeof DocsRoute
  FeedRoute: typeof FeedRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LegalRoute: typeof LegalRoute
  PortfolioRoute: typeof PortfolioRoute
  PricingRoute: typeof PricingRoute
  ReferralsRoute: typeof ReferralsRoute
  RouterRoute: typeof RouterRoute
  SwapRoute: typeof SwapRoute
  ApiMcpRoute: typeof ApiMcpRoute
  TokenMintRoute: typeof TokenMintRoute
  ApiActionsSubscribeRoute: typeof ApiActionsSubscribeRoute
  ApiCronTasksRoute: typeof ApiCronTasksRoute
  ApiLicensesConfirmRoute: typeof ApiLicensesConfirmRoute
  ApiPublicAgentRunRoute: typeof ApiPublicAgentRunRoute
  ApiPublicRouterPartnerRoute: typeof ApiPublicRouterPartnerRoute
  ApiPublicWebhooksHeliusRoute: typeof ApiPublicWebhooksHeliusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/swap': {
      id: '/swap'
      path: '/swap'
      fullPath: '/swap'
      preLoaderRoute: typeof SwapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/router': {
      id: '/router'
      path: '/router'
      fullPath: '/router'
      preLoaderRoute: typeof RouterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baskets': {
      id: '/baskets'
      path: '/baskets'
      fullPath: '/baskets'
      preLoaderRoute: typeof BasketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token/$mint': {
      id: '/token/$mint'
      path: '/token/$mint'
      fullPath: '/token/$mint'
      preLoaderRoute: typeof TokenMintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baskets/$id': {
      id: '/baskets/$id'
      path: '/$id'
      fullPath: '/baskets/$id'
      preLoaderRoute: typeof BasketsIdRouteImport
      parentRoute: typeof BasketsRoute
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/licenses/confirm': {
      id: '/api/licenses/confirm'
      path: '/api/licenses/confirm'
      fullPath: '/api/licenses/confirm'
      preLoaderRoute: typeof ApiLicensesConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/tasks': {
      id: '/api/cron/tasks'
      path: '/api/cron/tasks'
      fullPath: '/api/cron/tasks'
      preLoaderRoute: typeof ApiCronTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/actions/subscribe': {
      id: '/api/actions/subscribe'
      path: '/api/actions/subscribe'
      fullPath: '/api/actions/subscribe'
      preLoaderRoute: typeof ApiActionsSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/helius': {
      id: '/api/public/webhooks/helius'
      path: '/api/public/webhooks/helius'
      fullPath: '/api/public/webhooks/helius'
      preLoaderRoute: typeof ApiPublicWebhooksHeliusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/router/partner': {
      id: '/api/public/router/partner'
      path: '/api/public/router/partner'
      fullPath: '/api/public/router/partner'
      preLoaderRoute: typeof ApiPublicRouterPartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent/run': {
      id: '/api/public/agent/run'
      path: '/api/public/agent/run'
      fullPath: '/api/public/agent/run'
      preLoaderRoute: typeof ApiPublicAgentRunRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BasketsRouteChildren {
  BasketsIdRoute: typeof BasketsIdRoute
}

const BasketsRouteChildren: BasketsRouteChildren = {
  BasketsIdRoute: BasketsIdRoute,
}

const BasketsRouteWithChildren =
  BasketsRoute._addFileChildren(BasketsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BasketsRoute: BasketsRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DocsRoute: DocsRoute,
  FeedRoute: FeedRoute,
  LeaderboardRoute: LeaderboardRoute,
  LegalRoute: LegalRoute,
  PortfolioRoute: PortfolioRoute,
  PricingRoute: PricingRoute,
  ReferralsRoute: ReferralsRoute,
  RouterRoute: RouterRoute,
  SwapRoute: SwapRoute,
  ApiMcpRoute: ApiMcpRoute,
  TokenMintRoute: TokenMintRoute,
  ApiActionsSubscribeRoute: ApiActionsSubscribeRoute,
  ApiCronTasksRoute: ApiCronTasksRoute,
  ApiLicensesConfirmRoute: ApiLicensesConfirmRoute,
  ApiPublicAgentRunRoute: ApiPublicAgentRunRoute,
  ApiPublicRouterPartnerRoute: ApiPublicRouterPartnerRoute,
  ApiPublicWebhooksHeliusRoute: ApiPublicWebhooksHeliusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
